build:
  image: framgia/laravel
  environment:
    - DB_HOST=localhost
    - DB_DATABASE=demo
    - DB_USERNAME=root
    - DB_PASSWORD=root
  commands:
    - supervisord &
    - chmod -R 777 storage/
    - chmod -R 777 bootstrap/cache/
    - cp .env.testing .env
    - composer install
    - sleep 15
    - mysql -u$DB_USERNAME -p$DB_PASSWORD -e "CREATE DATABASE $DB_DATABASE CHARACTER SET utf8;"
    - php artisan migrate
    - vendor/bin/phpunit
publish:
  docker:
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    when:
      branch: develop
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: framgia/laravel-cd-demo
    file: Dockerfile.staging
    tag: staging
  docker:
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    when:
      branch: [master, release]
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: framgia/laravel-cd-demo
    file: Dockerfile.production
    tag: latest
deploy:
  rancher:
    url: $$RANCHER_URL
    access_key: $$RANCHER_ACCESS_KEY
    secret_key: $$RANCHER_SECRET_KEY
    service: $$RANCHER_SERVICE_STAGING
    docker_image: framgia/laravel-cd-demo:staging
    when:
      branch: develop
  rancher:
    url: $$RANCHER_URL
    access_key: $$RANCHER_ACCESS_KEY
    secret_key: $$RANCHER_SECRET_KEY
    service: $$RANCHER_SERVICE_PRODUCTION
    docker_image: framgia/laravel-cd-demo:latest
    when:
      branch: [master, release]
cache:
  mount:
    - .git
    - vendor
