build:
  image: framgia/laravel
  environment:
    - APP_ENV=testing
    - APP_KEY=base64:3Qnvvim9MN5zjCg3M0cy1ATy/qWISiJOldYPIv3hq5g=
    - DB_HOST=localhost
    - DB_DATABASE=demo
    - DB_USERNAME=root
    - DB_PASSWORD=root
    - CACHE_DRIVER=file
    - SESSION_DRIVER=file
    - QUEUE_DRIVER=sync
  commands:
    - supervisord &
    - chmod -R 777 storage/
    - chmod -R 777 bootstrap/cache/
    - composer install
    - mysql -u$DB_USERNAME -p$DB_PASSWORD -e "CREATE DATABASE $DB_DATABASE CHARACTER SET utf8;"
    - php artisan migrate
    - vendor/bin/phpunit
publish:
  docker:
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: framgia/laravel-cd-demo
    tag:
      - latest
      - production
    file: Dockerfile
    insecure: false
    load: docker-build/laravel-cd-demo.tar
    save:
      destination: docker-build/laravel-cd-demo.tar
      tag: latest
cache:
  mount:
    - docker-build/laravel-cd-demo.tar
