build:
  image: framgia/laravel
  environment:
    - APP_ENV=testing
    - APP_KEY=base64:3Qnvvim9MN5zjCg3M0cy1ATy/qWISiJOldYPIv3hq5g=
    - DB_HOST=localhost
    - DB_DATABASE=demo
    - DB_USERNAME=root
    - DB_PASSWORD=root
    - CACHE_DRIVER=file
    - SESSION_DRIVER=file
    - QUEUE_DRIVER=sync
  commands:
    - chmod -R 777 storage/
    - chmod -R 777 bootstrap/cache/
    - composer install
    - vendor/bin/phpunit
