build:
  image: framgia/laravel-workspace
  commands:
    - sleep 10
    - chmod -R 777 storage/
    - chmod -R 777 bootstrap/cache/
    - composer install
    - npm install
    - gulp
    - cp .env.testing .env
    - php artisan migrate --database=mysql_test
    - vendor/bin/phpunit
compose:
  database:
    image: mysql
    environment:
      MYSQL_DATABASE: demo
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root
publish:
  docker:
    storage_path: /drone/docker
    when:
      branch: develop
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: framgia/laravel-cd-demo
    file: Dockerfile.staging
    tag: staging
  docker:
    storage_path: /drone/docker
    when:
      branch: [master, release]
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: framgia/laravel-cd-demo
    file: Dockerfile.production
    tag: latest
deploy:
  rancher:
    url: $$RANCHER_URL
    access_key: $$RANCHER_ACCESS_KEY
    secret_key: $$RANCHER_SECRET_KEY
    service: $$RANCHER_SERVICE_STAGING
    docker_image: framgia/laravel-cd-demo:staging
    when:
      branch: develop
  rancher:
    url: $$RANCHER_URL
    access_key: $$RANCHER_ACCESS_KEY
    secret_key: $$RANCHER_SECRET_KEY
    service: $$RANCHER_SERVICE_PRODUCTION
    docker_image: framgia/laravel-cd-demo:latest
    confirm: true
    when:
      branch: [master, release]
notify:
  email:
    from: $$EMAIL_FROM
    host: $$EMAIL_HOST
    username: $$EMAIL_USERNAME
    password: $$EMAIL_PASSWORD
    recipients:
      - $$EMAIL_RECIPIENTS
cache:
  mount:
    - .git
    - vendor
    - node_modules
    - /drone/docker
