build:
  image: framgia/laravel
  environment:
    - DB_HOST=localhost
    - DB_DATABASE=demo
    - DB_USERNAME=root
    - DB_PASSWORD=root
  commands:
    - supervisord &
    - chmod -R 777 storage/
    - chmod -R 777 bootstrap/cache/
    - cp .env.testing .env
    - composer install
    - sleep 15
    - mysql -u$DB_USERNAME -p$DB_PASSWORD -e "CREATE DATABASE $DB_DATABASE CHARACTER SET utf8;"
    - php artisan migrate
    - vendor/bin/phpunit
cache:
  mount:
    - .git
    - vendor
